### ISSUE TITLE
Unable to see results when a symbol is in search

### ISSUE THREAD

**Issue by HanukkahJamboree** [TarballCoLtd/REDSwift#1]
Attempting to search "A&M 50" returned no results in the app, but navigating to Redacted directly returns torrent results. See attached images.
![332140816_759569945359927_8908769533532533781_n](https://user-images.githubusercontent.com/1761878/222548479-bfb14bb5-bae3-4503-8a00-ad186d4a51d1.jpg)
![image](https://user-images.githubusercontent.com/1761878/222548605-db279300-181a-4717-ace4-c5c4afc6548e.png)

**Comment by alyxandraio** [comment]
Sorry this took me so long to see! Not sure why GitHub didn't notify me. I'll look into escaping special characters.

**Comment by alyxandraio** [comment]
Fixed in dev with commit https://github.com/TarballCoLtd/GazelleKit/commit/c4c1f9db00e88c135841955e5d298bf951c5f79a
